name: Code Coverage
'on':
  - pull_request
jobs:
  build:
    name: Calculate code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install volta
        uses: volta-cli/action@v1
      - name: Install dependencies
        run: yarn install
      - name: Compare code coverage
        uses: mydea/ember-cli-code-coverage-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          test-command: "yarn test:ember:coverage"
